version: "2.1"

networks:
  rede_app:

volumes:
  vol_app_mongo:  
  vol_app_postgre:

services:
  mongo:
    image: mongo:5.0.8
    container_name: banco_mongo
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    expose:
      - "27017"
    networks: 
      - rede_app
    volumes:
      - vol_app_mongo:/data/db
    
  movie:
    image: felipejm91/movie:v1
    container_name: movie
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      MONGODB_URI: ${MONGODB_URI}
    expose:
      - "8181"
    networks:
      - rede_app
    

  postgre:
    image: postgres:14.2
    container_name: banco_postgre
    networks:
      - rede_app
    volumes:
      - vol_app_postgre:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    

  review:
    image: felipejm91/review:v1
    container_name: review
    depends_on:
      - postgre
    networks:
      - rede_app
    expose:
      - "80"
    env_file:
      - .env
    environment:
      ConnectionStrings__MyConnection: ${ConnectionStrings__MyConnection}


  app_python:
    image: felipejm91/rotten-potatoes-ms:v1
    container_name: app_python
    depends_on:
      - mongo
      - postgre
      - movie
      - review
    ports:
      - "8080:5000"
    env_file:
      - .env
    environment:
      MOVIE_SERVICE_URI: ${MOVIE_SERVICE_URI}
      REVIEW_SERVICE_URI: ${REVIEW_SERVICE_URI}
    networks:
      - rede_app
    